"""empty message

Revision ID: f7ff5908f7a8
Revises: 39b4e9e1f038
Create Date: 2017-05-26 22:49:45.022245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ff5908f7a8'
down_revision = '39b4e9e1f038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('timer', sa.Time(), nullable=False),
    sa.Column('start_datetime_at', sa.DateTime(), nullable=True),
    sa.Column('due_datetime_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pomodoro_activities')
    # ### end Alembic commands ###
