--DROP DATABASE IF EXISTS focus;
--CREATE DATABASE focus;
--CREATE USER focus WITH ENCRYPTED PASSWORD 'focus';
--                               dbname to username
--GRANT ALL PRIVILEGES ON DATABASE focus TO focus;